[workspace]
members = ["machine", "derive"]
resolver = "2"

[patch."https://github.com/Plonky3/Plonky3"]
p3-air = { path = "../Plonky3/air" }
p3-challenger = { path = "../Plonky3/challenger" }
p3-commit = { path = "../Plonky3/commit" }
p3-dft = { path = "../Plonky3/dft" }
p3-field = { path = "../Plonky3/field" }
p3-fri = { path = "../Plonky3/fri" }
p3-keccak = { path = "../Plonky3/keccak" }
p3-keccak-air = { path = "../Plonky3/keccak-air" }
p3-matrix = { path = "../Plonky3/matrix" }
p3-merkle-tree = { path = "../Plonky3/merkle-tree" }
p3-symmetric = { path = "../Plonky3/symmetric" }
p3-uni-stark = { path = "../Plonky3/uni-stark" }
